services:
- docker
branches:
  only:
  - master
stages:
- unit
- integration
jobs:
  include:
  - stage: unit
    name: Run Unit Tests
    script:
    - make unit
  - stage: integration
    name: Run Integration Tests
    script:
    - make integration
before_install:
- openssl aes-256-cbc -K $encrypted_342f2f6ad141_key -iv $encrypted_342f2f6ad141_iv
  -in .env_info.enc -out .env_info -d
