version: "2.4"
services:
  travis-ci:
    image: skandyla/travis-cli
    volumes:
      - "$HOST_PWD:/work"
    working_dir: /work
    environment:
      - TRAVIS_GITHUB_TOKEN
  aws:
    image: amazon/aws-cli:2.2.9
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    volumes:
      - "${HOST_PWD}:/work"

  gomplate:
    image: hairyhenderson/gomplate:v3.10.0-alpine
    environment:
      - GOMPLATE_SUPPRESS_EMPTY=true

  hugo:
    build:
      dockerfile: hugo.dockerfile
      args:
        - HUGO_VERSION=0.66.0
      context: .
    tty: true
    volumes:
      - "${HOST_PWD}/site:/site"
      - "${HOST_PWD}/content:/site/content"
      - "${HOST_PWD}/layouts/:/site/layouts"
      - "${HOST_PWD}/themes/:/site/themes"
      - "${HOST_PWD}/static/:/site/static"
      - "${HOST_PWD}/config.toml:/site/config.toml"
    working_dir: /site

  terraform:
    image: carlosnunez/terraform:1.0.11
    volumes:
      - "${HOST_PWD}/infrastructure/${INFRASTRUCTURE_PROVIDER}:/work"
    working_dir: /work
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_SESSION_TOKEN
      - TF_INPUT=0
      - TF_CLI_ARGS_init=-backend=true -backend-config=backend.tfvars -reconfigure
      - TF_CLI_ARGS_plan=-lock=false -auto-approve=true
      - TF_CLI_ARGS_apply=-lock=false -auto-approve=true
      - TF_CLI_ARGS_destroy=-lock=false -auto-approve=true

  obtain-aws-session-credentials:
    extends: aws
    command:
      - sts
      - assume-role
      - --role-arn
      - "$AWS_ROLE_ARN"
      - --external-id
      - "$AWS_STS_EXTERNAL_ID"
      - --role-session-name
      - "$AWS_SESSION_NAME"
      - --output
      - json
