version: "2.4"
services:
  hugo-base:
    build:
      context: .
      args:
        - HUGO_VERSION

  hugo-generate-configs:
    image: hairyhenderson/gomplate
    env_file: .env
    volumes:
      - "${PWD}:/work"
    working_dir: /work
    command:
      - "-V"
      - "--file"
      - config.toml.tmpl
      - "--out"
      - config.toml

  hugo-generate-test-configs:
    extends: hugo-generate-configs
    env_file: .env.test

  hugo:
    extends: hugo-base
    env_file: .env
    tty: true
    volumes:
      - "${PWD}/site:/site"
      - "${PWD}/layouts/:/site/layouts"
      - "${PWD}/themes/:/site/themes"
      - "${PWD}/posts/:/site/content"
      - "${PWD}/config.toml:/site/config.toml"
    working_dir: /site
    ports:
      - 8080:8080
    command:
      - server
      - --baseURL
      - "${HUGO_BASE_URL}"
      - --bind
      - "0.0.0.0"
      - -p
      - "8080"

  hugo-tests:
    extends: hugo
    env_file: .env.test
    volumes:
      - "${PWD}/tests/fixtures/test_posts/:/site/content"
