version: "2.6"
services:
  hugo:
    build:
      context: .
      args:
        - HUGO_VERSION=${HUGO_VERSION:?Please define the version of Hugo to install.}
    tty: true
    env_file:
      - ${ENVIRONMENT_FILE:?Please define an environment file.}
    environment:
      - HUGO_BASE_URL=http://localhost
    volumes:
      - "${PWD}/site:/site"
      - "${PWD}/layouts:/site/layouts"
      - "${PWD}/themes:/site/themes"
      - "${PWD}/posts:/site/content"
      - "/dev/null:/site/config.toml"
    working_dir: /site
    ports:
      - 8080:8080
    command: "server --baseURL ${HUGO_BASE_URL} --bind 0.0.0.0 -p 8080"
  hugo_tests:
    extends:
      - hugo
    volumes:
      - "${PWD}/tests/fixtures/test_posts:/site/content"
