version: "2.4"
services:
  update-ci-env-info:
    image: skandyla/travis-cli
    volumes:
      - "$PWD:/work"
    working_dir: /work
    environment:
      - TRAVIS_GITHUB_TOKEN
    entrypoint: "sh -c 'travis login --github-token $TRAVIS_GITHUB_TOKEN && travis encrypt-file -a before_install .env_info'"
