version: "2.4"
services:
  generate-terraform-tfvars:
    extends: gomplate
    env_file: .env
    volumes:
      - "$PWD/infrastructure/${INFRASTRUCTURE_PROVIDER}:/work"
      - "$PWD/.env:/.env"
    working_dir: /work
    command:
      - "--file"
      - terraform.tfvars.tmpl
      - "--out"
      - terraform.tfvars

  generate-terraform-backend:
    extends: gomplate
    env_file: .env
    volumes:
      - "$PWD/infrastructure/${INFRASTRUCTURE_PROVIDER}:/work"
      - "$PWD/.env:/.env"
    working_dir: /work
    command:
      - "--file"
      - backend.tf.tmpl
      - "--out"
      - backend.tf

  generate-terraform-backend-vars:
    extends: gomplate
    env_file: .env
    volumes:
      - "$PWD/infrastructure/${INFRASTRUCTURE_PROVIDER}:/work"
      - "$PWD/.env:/.env"
    working_dir: /work
    command:
      - "--file"
      - backend.tfvars.tmpl
      - "--out"
      - backend.tfvars

  generate-terraform-unit-test-tfvars:
    extends: gomplate
    env_file: .env.test
    volumes:
      - "$PWD/infrastructure/${INFRASTRUCTURE_PROVIDER}:/work"
      - "$PWD/.env.test:/.env"
    working_dir: /work
    command:
      - "--file"
      - terraform.tfvars.tmpl
      - "--out"
      - terraform.tfvars

  generate-terraform-unit-test-backend:
    volumes:
      - "$PWD/infrastructure/${INFRASTRUCTURE_PROVIDER}:/work"
      - "$PWD/tests:/tests"
    image: alpine
    entrypoint: "sh -c 'cp /tests/fixtures/backend.tf /work/backend.tf && touch /work/backend.tfvars'"

  terraform_debug:
    extends: terraform
    environment:
      - TF_LOG=DEBUG
